---
- name: create directory 
  become: true
  file: 
    path: /home/ubuntu/web
    state: directory
    mode: 0755

- name: copy artifact
  become: true
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/web/artifact.tar.gz

- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu/web
    tar -xvf artifact.tar.gz

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "start app"
  shell: |
    cd /home/ubuntu/web
    pm2 stop default
    pm2 start npm -- start